### PR TITLE
fix: install wizard bugs

### PR DESCRIPTION
**Pull request by ivelin**
## Purpose
During testing with John Senay today, we ran into two issues during the install steps.

1. The PWA install step quietly failed leaving the user with the impression that the PWA was installed. (See screenshot)
2. Discovery of local device was not triggered in the background even though the UI button indicated that a local device is being discovered.

## Approach
1. Add more robust edge case and error handling for the PWA install step.
2. Request explicit edge device discovery from the PnP API instead of relying on default behavior.

## Merge Checklist
- [x]  The code change is tested and works locally.
- [x]  The user and dev documentation is up to date.
- [x]  There is no commented out code in this PR.
- [x]  No lint errors (use flake8)
- [x]  100% test coverage

screen_shot_2021-08-20_at_1 17 57_pm

### CODE REVIEW

**Comment by ivelin** [comment]
@vickywane take a quick look at this one. I still have to add test cases.

**Comment by vickywane** [comment]
Currently going through. 

From the `installApp` method within the `onboarding` component, i can see there has been a change to the [beforeinstallprompt](https://web.dev/customize-install/) event from the last time i wrote the component. 

Previously, the design was to make the install prompt event available when is not installed on a device, and when installed, the event would be set to `null` hence the `try/catch` block.

**Comment by vickywane** [comment]
I will have to pull down your new implementation and test locally before adding comments on this pull request.

**Comment by ivelin** [comment]
> Currently going through.
> 
> From the `installApp` method within the `onboarding` component, i can see there has been a change to the [beforeinstallprompt](https://web.dev/customize-install/) event from the last time i wrote the component.
> 
> Previously, the design was to make the install prompt event available when is not installed on a device, and when installed, the event would be set to `null` hence the `try/catch` block.

Right. The problem was that on devices that do not support pwa install, the exception masked the issue and the install button continues with the message "You can now run this as a native app." which was false. Hence the change in logic. We still need an extensive testsuite to cover all the likely and edge scenarios. Work in progress.

**Pull request merged**
