### PR TITLE
Creates lighthouse ci

### PR DESCRIPTION
**Pull request by sniperadmin**
image

### CODE REVIEW

**Comment by ivelin** [comment]
@sniperadmin looks like you have been able to test Lighthouse on your local branch CI and all is fine. Should I pull the trigger for the master branch?

**Comment by sniperadmin** [comment]
it is now complete yes..
let's Fire in the Hole 💯

**Comment by ivelin** [comment]
OK, just to be clear. Accept this PR and close #346 , correct?

**Comment by sniperadmin** [comment]
correct

**Comment by ivelin** [comment]
Here we go :)

**Comment by ivelin** [comment]
@sniperadmin 
OK, the merge seems to work. The Lighthouse CI action passes on master, which is good. However I just noticed two issues:

1. The lighthouse script executes against ui.ambianic.ai , which is not the goal, right? It should execute against the code in a PR or a new commit against master.

2. Why does Lighthouse CI pass against the current version of ui.ambianic.ai when we know it regressed the PWA certification? :)

I am opening a new ticket to address these two issues. Will assign to you if you are ok with that.

**Comment by sniperadmin** [comment]
@ivelin 
Wow, cool! at least we moved a step forward
1. if we can access the build version at netlify, i guess we can include the new build in the url
2. will check about that regression

let's open the tickets :)

**Comment by ivelin** [comment]
Definitely a big step forward.

Adding more comments in the new issue #363

**Comment by ivelin** [comment]
Related to 1.

1.a. Normally the lighthouse script should run similar to unit testing and e2e testing. Against a locally started copy of the code on the PR or commit branch. 

Running against Netlify is also an option, but that introduces more variables in the equation. 

Thinking a bit more about it, maybe we should have it run against both the local copy and netlify preview deployment to ensure that the Netlify deployment environment doesn't introduce any unexpected PWA issues.

See the main [CI script](https://github.com/ambianic/ambianic-ui/blob/master/.github/workflows/nodejs.yml) for an example how cypress e2e tests run against a local copy of the PWA deployed in the CI environment:

```
 - name: End-to-end Tests with Cypress
      uses: cypress-io/github-action@v1
      with:
        start: npm run serve
        record: true
        wait-on: 'http://localhost:8080'
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

1.b If the Lighthouse check fails, it should stop a release. 
Currently the Lighthouse CI script runs independently of the main script where semantic release is triggered. 

We can adjust this one of two ways: either the Lighthouse script can go in the main script as a step before semantic release or we can use [action trigger events](https://help.github.com/en/actions/reference/events-that-trigger-workflows) to enforce the dependency.

**Pull request merged**
