### PR TITLE
fix: setups lighthouse-ci

### PR DESCRIPTION
**Pull request by sniperadmin**
hope this config works...

### CODE REVIEW

**Comment by ivelin** [comment]
Thank you! That was quick. 

We’re you able to run it on your fork to verify that it works? 

Since it will likely fail the CI until we find and fix regressions, this PR on master would end up having multiple commits. 

We can work on gradually fixing lighthouse certification errors on your fork until we end up with a PR that passes the master branch CI. 

Does that make sense?

**Comment by sniperadmin** [comment]
it does! it didn't work for sorrow ...

**Comment by ivelin** [comment]
Thank you @sniperadmin. Have you had a chance to test this action on your fork of ambianic-ui?

**Comment by sniperadmin** [comment]
for some reason, I am not able to view this pr in my fork
image

**Comment by ivelin** [comment]
The PR is against the master branch of the original repo, not the fork. You'd have to push a separate PR for your fork.

**Comment by sniperadmin** [comment]
I have checked repo settings, and it is linked to my forked one,.. 
image

I think I may close this one, and create a new pr... Any thoughts?

**Comment by ivelin** [comment]
Not quite clear from the messages, but it seems like somehow this PR for the main project master got entangled with commits intended for your fork. Probably easier to close this one and test a PR against your fork separately. Once confirmed that its working, re-open a PR for master.

**Pull request closed without merging**
