### PR TITLE
feat: change theme colors

### PR DESCRIPTION
**Pull request by sniperadmin**
this is a suggested theme for our app (can be recutomized):

image
image
image
image
image
image

### CODE REVIEW

**Comment by geekyahmed** [comment]
The theme makes sense no doubt but I suggest the cards have some border
radius and maybe box shadowing to make it look interactive

**Comment by sniperadmin** [comment]
cool, let's do that together, and feel free to add your touches

**Comment by geekyahmed** [comment]
Sure.

No problems

**Comment by ivelin** [comment]
Cool alternative themes. Looks like the CI is failing. Can you look at that before we proceed with the review and merge?
https://github.com/ambianic/ambianic-ui/pull/445/checks?check_run_id=1453222635

**Comment by BKristenssonAlfsson** [comment]
The failing CI might be because of this:
https://github.com/puppetlabs/action-litmus_spec/issues/59

It should have been solved, so a simple restart might let it pass

**Review by BKristenssonAlfsson — APPROVED** [review]
Looks good for me

**Review by ivelin — APPROVED** [review]
Looks good. Merging.

**Comment by ivelin** [comment]
@sniperadmin , @geekyahmed 

After I merged this PR, I remembered that the CI currently runs Lighthouse against the live site and not the PR code. Which means I don't know if the colorblind contrast requirements are met.

Would one of you be interested in taking on [this issue](https://github.com/ambianic/ambianic-ui/issues/485) to make sure that we don't regress? Looks like there are several popular github actions now that make it easy to run lighthouse in a local CI host.

**Pull request merged**
