### PR TITLE
fix: Show version info in About page

### PR DESCRIPTION
**Pull request by Alexander-Bliznyuk**

### CODE REVIEW

**Comment by ivelin** [comment]
Looks great, @Alexander-Bliznyuk . Thank you!

**Comment by ivelin** [comment]
I am accepting this pull request. Would you mind adding a test case to the Cypress testsuite to cover this feature?

**Comment by Alexander-Bliznyuk** [comment]
> I am accepting this pull request. Would you mind adding a test case to the Cypress testsuite to cover this feature?

I don't mind and will add tomorrow.

**Comment by ivelin** [comment]
Awesome! Thank you.

**Pull request merged**
