### PR TITLE
feature: adds ui-tests

### PR DESCRIPTION
**Pull request by sniperadmin**
image

### CODE REVIEW

**Comment by sniperadmin** [comment]
just tested one commit, I will complete the ui tests, happy to receive comments and guidance :)

**Comment by ivelin** [comment]
Nice start! Congrats! 

We use semantic release convention for commits. When adding tests the prefix to use is “test:”. 


feat (feature)
fix (bug fix)
docs (documentation)
style (formatting, missing semi colons, …)
refactor
test (when adding missing tests)
chore (maintain)


I will correct this in the merge.

**Comment by sniperadmin** [comment]
Great! will keep that in mind for sure!

**Pull request merged**
