### PR TITLE
ci: fix breaking lighthouse checks

### PR DESCRIPTION
**Pull request by vickywane**
The goal of opening this pull request is to use it as a rough pull request to trigger the Lighthouse CI until it passes then I can clean up in a new PR. After the Lighthouse check passes, I would close and continue work done in an organized pull request.

### CODE REVIEW

**Comment by ivelin** [comment]
@vickywane the PR description template is there for a reason. Fill it in.

**Comment by vickywane** [comment]
@ivelin 

I want to use this pull request to figure out why the checks are failing first. All fixes made haven't worked yet so I might need to rewind the app till I figure out where the break is from. 

TL;DR : 
I plan using this as a rough pull request to trigger the Lighthouse CI until it passes then I can clean up in a new PR

**Comment by ivelin** [comment]
@vickywane is this PR still active?

**Comment by vickywane** [comment]
No it isn't as the lighthouse checks failure has been automatically fixed.

**Pull request closed without merging**
