### PR TITLE
feat: convenient copy paste button for edge device ID

### LINKED ISSUE #512: feat: add copy button next to edge peer id
**Is your feature request related to a problem? Please describe.**
Currently we allow users to share their peer id with other remote users in order to give them access to edge device timeline data. This requires the sharing user to go to the edge device settings page, copy and paste the id and then send a message to the requesting user. 

**Describe the solution you'd like**

With the current peer id field, the ID is hidden by default as it is sensitive information. It would be convenient to implement a [standard copy button](https://material.io/resources/icons/?search=copy&icon=content_copy&style=baseline) next to the eye (reveal) button which copies the peer id to the clipboard for sharing. 

**Describe alternatives you've considered**

This would be an intermediate convenience option that would be later replaced by a sharing button as discussed in #327 .

**Additional context**
Reference screenshot below.

IMG_5447

### PR DESCRIPTION
**Pull request by ivelin**
Closes #512 

## Purpose
Currently if the user wants to share an edge device ID with a trusted family member or friend, they need to go to the Settings page and click on the eye icon next to the Edge Peer ID field. That would show the clear text value of the label which the user can select and copy to clipboard then share. Selecting the full value of the text field is cumbersome on mobile devices because it often goes beyond the screen size and requires drag to scroll and select.

## Approach
Add a convenient copy/paste button next to the Edge Peer ID field so the user can copy the value with one click and share it.

#### Open Questions and Pre-Merge TODOs
- [X] Use github checklists. When solved, check the box and explain the answer.

## Merge Checklist
- [X]  The code change is tested and works locally.
- [X]  The user and dev documentation is up to date.
- [X]  There is no commented out code in this PR.
- [X]  No lint errors (use flake8)
- [X]  100% test coverage

### CODE REVIEW

**Comment by vickywane** [comment]
@ivelin I will pull your branch and test locally in some hours. 

In the meantime, can you add some e2e tests to assert the copy icon is shown?

**Comment by ivelin** [comment]
Yes, good idea.

**Comment by ivelin** [comment]
This codecov comment above shows a big drop in coverage but that is outdated. There was an issue with the codecov upload which was fixed. [The latest uploaded report ](https://app.codecov.io/gh/ambianic/ambianic-ui) shows tests are back to 85% coverage. See screenshot below.

Screen Shot 2021-08-14 at 6 22 20 PM


> # [Codecov](https://codecov.io/gh/ambianic/ambianic-ui/pull/699?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ambianic) Report

**Review by vickywane — COMMENTED** [review]
I have just tested out this feature, and it works as described. 

However, I have some UI & UX-related reservations;

- As shown in the attached image, there's a huge gap between the existing visibility Icon and the new copy icon. They should be much closer.

- Can we add labels to these icons? Although the icons' shapes are explanatory, it could be difficult for new users to decipher their use the first glance. An example label could be gotten from the [Tooltip component](https://vuetifyjs.com/en/components/tooltips/).

**Comment by ivelin** [comment]
> I have just tested out this feature, and it works as described.
> 
> However, I have some UI & UX-related reservations;
> 
> * As shown in the attached image, there's a huge gap between the existing visibility Icon and the new copy icon. They should be much closer.

@vickywane Did you mean to attach screenshots? I don't see any.

> * Can we add labels to these icons? Although the icons' shapes are explanatory, it could be difficult for new users to decipher their use the first glance. An example label could be gotten from the [Tooltip component](https://vuetifyjs.com/en/components/tooltips/).

Good idea. I'll add tooltips.

**Comment by vickywane** [comment]
Exactly. 

It's styling-related. 
Since we now have two icons, we can put the two icons on a separate line for both small and large screens.

**Comment by ivelin** [comment]
> Exactly.
> 
> It's styling-related.
> Since we now have two icons, we can put the two icons on a separate line for both small and large screens.

Done. 

Added tooltips as well. 

Waiting on CI results.

**Review by vickywane — APPROVED** [review]
I just pulled and test locally again. 
The styling issue has been fixed, and it works as expected.

Looks okay for a merge.

**Pull request merged**
